import "./modules/swiper.min.js";
import catalogMenu from "./modules/catalogMenu.js";
import footerMenu from "./modules/footerMenu.js";
import headerMenu from "./modules/headerMenu.js";
import headerScroll from "./modules/headerScroll.js";
import heroSwiper from "./modules/heroSwiper.js";
import goodsCardHandler from "./modules/goodsCardHandler.js";
import filterHandler from "./modules/filterHandler.js";
import transportCompanes from "./modules/transportCompanesSwiper.js";
import goodsListSwiper from "./modules/goodsListSwiper.js";
import newsSwiper from "./modules/newsSwiper.js";
import filterPopupHandler from "./modules/filterPopupHandler.js";
import filterPopupScroll from "./modules/filterPopupScroll.js";
import multiRangeHandler from "./modules/multiRangeHandler.js";
import massagePopupHendler from "./modules/massagePopupHendler.js";
import switchTypeInput from "./modules/switchTypeInput.js";
import checkoutFormHandler from "./modules/checkoutFormHandler.js";
import productSwiperMain from "./modules/productSwiperMain.js";
import productHandler from "./modules/productHandler.js";
import newsAsideSwiper from "./modules/newsAsideSwiper.js";
import productInfoSwiper from "./modules/productInfoSwiper.js";
import cartScroll from "./modules/cartScroll.js";
import teamSwiper from "./modules/teamSwiper.js";
import advantageSwiper from "./modules/advantageSwiper.js";
import contactsDetailsHandler from "./modules/contactsDetailsHandler.js";
import paymentTablesHandler from "./modules/paymentTablesHandler.js";
import maskPhone from "./modules/maskphone.js";
import textareaHeightControler from "./modules/textareaHeightControler.js";
import cartHandler from "./modules/cartHandler.js";
import modalsHandler from "./modules/modalsHandler.js";

headerScroll();
headerMenu();
catalogMenu();
filterHandler()
filterPopupHandler();
multiRangeHandler();
filterPopupScroll();
heroSwiper();
newsSwiper();
goodsCardHandler();
goodsListSwiper();
transportCompanes();
footerMenu();
massagePopupHendler();
switchTypeInput();
checkoutFormHandler();
productSwiperMain();
productHandler();
productInfoSwiper();
newsAsideSwiper();
cartScroll();
cartHandler();
teamSwiper();
advantageSwiper();
contactsDetailsHandler();
paymentTablesHandler();
maskPhone('input[name="phone"]');
textareaHeightControler();
modalsHandler();
